services:
  test-debug:
    build: .
    ports:
      - "5678:5678"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONBREAKPOINT=debugpy.breakpoint
    command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m pytest -v tests/