services:
  app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    volumes:
      - .:/app
    environment:
      - PYTHONBREAKPOINT=${PYTHONBREAKPOINT}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - DEBUG_PORT=${DEBUG_PORT}
    command: ${DOCKER_CMD}